### ISSUE TITLE
Provide order note with error if OM call fails

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-order-management-for-woocommerce#1]
Steps to recreate:
1. create order
2. capture order outside of Woo (e.g. via merchant portal, Postman, or Paw)
3. attempt to capture order in Woo

**Comment by slobodan** [comment]
Is this capture only? We already have that check:

https://github.com/krokedil/klarna-order-management-for-woocommerce/blob/develop/klarna-order-management-for-woocommerce.php#L266-L270

**Comment by kristibarbosky** [comment]
Closing ticket, test passed successfully:

![image](https://user-images.githubusercontent.com/15654455/29626419-a87c5798-87fc-11e7-9edd-1177b628a010.png)
