### ISSUE TITLE
Order management doesn't work if KP plugin is active but KP (or KCOv3) is not activated

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-order-management-for-woocommerce#10]
Reporting for a live merchant (relating to Klarna internal ticket: PI-267), but I was able to recreate this in my Woo test store as well:

1. place a KP order, e.g. see 140d9837-fc6a-5e90-804e-bbd6497e4b6c
2. disable KP 
![image](https://user-images.githubusercontent.com/15654455/38821403-68f1f26e-416e-11e8-9230-6044aaff2912.png)
3. change Woo order status from Processing to Completed.  The Woo order notes show an error: "Klarna order could not be captured due to an error."  No API call is sent to Klarna.
![image](https://user-images.githubusercontent.com/15654455/38821458-89f94034-416e-11e8-8a94-2b8cf40d5eb7.png)

Order management should still work even if the Klarna front end (KP or KCO) is not active.

**Comment by MichaelBengtsson** [comment]
This is now fixed in the current develop branch.

**Comment by kristibarbosky** [comment]
Thanks @MichaelBengtsson  - my tests passed successfully, see below.  Please go ahead and merge to master branch when appropriate.  Thanks for the quick turnaround on this!
capture KP order when KP is not enabled, order ID: 2fd7354e-c451-5065-a860-b8771ebb915b 
capture KP order when KP is enabled,  order ID: 65f6cf23-6d2c-53ed-bdfa-c6459a0bc590
capture KCO order when KCO is not enabled, order ID: 98dd2a44-3492-7c7e-b9b0-9eda61d82fac
