### ISSUE TITLE
Fix refund messaging if no capture has been made

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-order-management-for-woocommerce#12]
In this line https://github.com/krokedil/klarna-order-management-for-woocommerce/blob/e05f205a64f0d1d94dee82f909bbec50d3cc5d45/klarna-order-management-for-woocommerce.php#L356 it says:

_Klarna order has already been captured and cannot be refunded._ if _wc_klarna_capture_id is missing.

But if the id is missing no capture has been triggered from woocommerce yet. 

Instead it probably should say _Klarna order has not been captured and cannot be refunded._

**Comment by kristibarbosky** [comment]
Plugin code can't control the Woo pop-up error (that just says "An error occurred ...") so a Woo order note "Klarna order has not been captured and cannot be refunded." is added:
![image](https://user-images.githubusercontent.com/15654455/69433386-89716c00-0d09-11ea-826e-74cb3ca3f03c.png)
but the Woo order page must be reloaded for that new order note to be displayed.
