### ISSUE TITLE
Move Fraud functionality to KCO plugin?

### ISSUE THREAD

**Issue by NiklasHogefjord** [krokedil/klarna-order-management-for-woocommerce#13]
KCO orders can get stuck in fraud control. In this plugin we have a listener for updating the order when status changes in Klarnas system.

Some merchants don't use the order management plugin since they handle activations, cancelations and refunds from an ERP system instead. By having the fraud follow up logic in the OM plugin orders won't get updated in this scenario.

Do you think that we should move the fraud logic to KCO plugin @kristibarbosky?

**Comment by kristibarbosky** [comment]
Pending functionality can be used for both KCO & KP, so we didn't want to duplicate the logic.  Currently I think pending is used mainly (only?) in the US market though.  Perhaps a good discussion during our weekly status call?

**Comment by NiklasHogefjord** [comment]
Aha, I didn't realize that it was both KCO and KP. Let's discuss during the weekly call.

**Comment by kristibarbosky** [comment]
Per discussion during Sept. 27th, 2018 meeting, fraud functionality will stay in this OM plugin (since shared between KCO & KP), but enhancement will be include a config option for merchants to not utilize the OM functionality (capture, cancel, refund) if desired.

**Comment by NiklasHogefjord** [comment]
This is fixed in https://github.com/krokedil/klarna-order-management-for-woocommerce/releases/tag/1.3.0
