### ISSUE TITLE
Fraud risk rejected orders no longer updating Woo order status - 500 error

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-order-management-for-woocommerce#15]
Order stays stuck in "On Hold" status, but should be Cancelled (if not already captured) as rejected by Klarna (at least with an order note) and the notification should be successfully handled.

merchant_id:	 N100135	
  	 message:	 Notification request of type FRAUD_RISK_REJECTED for order id FRAUD_RISK_REJECTED returned an unexpected status. Status: 500, response body: '', URL: https://wptest.mageklarna.com/wc-api/WC_Gateway_Klarna_Payments/?order_id=1061	
  	 order_id:	 08af0d68-2e15-60e4-960c-10177898c5a9	
  	 timestamp:	 2018-10-17T19:26:53.179Z	
  	 uid:	 5ca36c1b-5cc7-4a4a-afd5-0fdfe2ebf9fe	

OM plugin Version 1.2.4
KP plugin Version 1.6.1

**Comment by MichaelBengtsson** [comment]
@kristibarbosky Did this happen when trying to activate the order?

**Comment by kristibarbosky** [comment]
No, the order never got updated when Klarna rejected it after Fraud review; the order stayed in "On Hold" status.

**Comment by kristibarbosky** [comment]
Retested today with KP, test order_id: 88ac3af7-5f8a-7727-a8ac-2244b2f6ff99 (order stayed "On Hold" )

message: Notification request of type FRAUD_RISK_REJECTED for order id 88ac3af7-5f8a-7727-a8ac-2244b2f6ff99 returned an unexpected status. Status: 500, response body: 

<body id="error-page">
	<div class="wp-die-message"><p>There has been a critical error on your website.</p><p><a href="https://wordpress.org/support/article/debugging-in-wordpress/">Learn more about debugging in WordPress.</a></p></div></body>
</html>
	', URL: http://readacted/wc-api/WC_Gateway_Klarna_Payments/?order_id=567

**Comment by MichaelBengtsson** [comment]
Fixed in the latest versions of the plugin. Probably solved with the changes done in version 1.5.3
