### ISSUE TITLE
Could OM via Woo admin work for orders added manually via Woo admin (and in Klarna via Seller's App)?

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-order-management-for-woocommerce#16]
Currently, when I create matching manual orders in 1) Klarna's playground merchant portal and 2) Woo test store admin (with KP as the payment method and adding the Klarna order_id as the Woo 'Transaction ID'), and then change the Woo order status to Completed, the order cannot be captured in Klarna.  I don't see a call to Klarna (in Splunk logs) for this capture attempt, so I suspect the problem is on the Woo side that perhaps it doesn't have all the data necessary for the order.  Could we enable this to work?  Do I need to set any other fields on the Woo order?

![image](https://user-images.githubusercontent.com/15654455/47520187-7c135500-d85d-11e8-9c8b-a7e5cd3a2cc3.png)

![image](https://user-images.githubusercontent.com/15654455/47520236-a402b880-d85d-11e8-9588-5dd941457907.png)

**Comment by NiklasHogefjord** [comment]
At the moment I don't think that this is possible. When reviewing this a bit closer it looks like SKU is not possible to add to the order line in the Sellers order in Merchant Portal.

![image](https://user-images.githubusercontent.com/985946/48493481-34646580-e82c-11e8-8d8e-f232cb516750.png)

I think we need SKU to be able to create the order correctly in Woo. @kristibarbosky perhaps you can check internally if this is on the roadmap?

**Comment by MichaelBengtsson** [comment]
Closed, we are now supporting this. Read more in our documentation. https://docs.krokedil.com/article/149-klarna-order-management#h-H2_7
