### ISSUE TITLE
Include amount of capture or refund in the Woo order note.

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-order-management-for-woocommerce#2]
Although Woo currently only provides full capture, it would still be helpful to easily see the amount of a order capture or order refund in the Woo order note.

**Comment by slobodan** [comment]
![screen shot 2017-09-01 at 11 42 40](https://user-images.githubusercontent.com/129607/29964555-b26f356c-8f0a-11e7-85ed-5af1a0c7ca68.png)

Adds WooCommerce order total, using `WC_Order->get_formatted_order_total()` function.

**Comment by slobodan** [comment]
Got closed automatically when I merged into master

**Comment by kristibarbosky** [comment]
Tests passed successfully:
![image](https://user-images.githubusercontent.com/15654455/30068493-f720f5dc-922b-11e7-8172-13de999d1a20.png)
