### ISSUE TITLE
OM logging still logged even when "Debug logging" not checked [PI-1260]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-order-management-for-woocommerce#29]
(tested with KP latest version):

![image](https://user-images.githubusercontent.com/15654455/70077208-5ca53a80-15ce-11ea-92d6-fb63375aa5fa.png)

![image](https://user-images.githubusercontent.com/15654455/70077266-7b0b3600-15ce-11ea-987e-1acd2722e5d2.png)

**Comment by MichaelBengtsson** [comment]
Fixed in d26ad6eec4b0fc56cb11993083d3202dd5e10b70
Separate setting for the plugin to avoid issues if you have had both KCO and KP installed at some point and still have settings stored in the database.

**Comment by MichaelBengtsson** [comment]
Fixed with version 1.5.2 with new setting.
