### ISSUE TITLE
Add support for partial capture 

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-order-management-for-woocommerce#3]
Currently only full captures are available in OM.   Could partial captures also be supported?

**Comment by slobodan** [comment]
No, there's no such functionality in WooCommerce, so unless we build this from scratch it won't work.

**Comment by kristibarbosky** [comment]
Closing this ticket as merchants can do partial capture thru Klarna merchant portal if necessary.  Per data from Order Mgmt product owner, partial capture is not a frequently used functionality, so it doesn't seem worth building into the OM plugin at this time.
