### ISSUE TITLE
Document required version of WooCommerce [PI-1312]

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-order-management-for-woocommerce#31]
Getting a 500 error when capturing a KP order.

VM2499 load-scripts.php:3 POST https://redacted.com/wp-admin/post.php 500 (Internal Server Error)

WC version:		3.1.2

**Comment by MichaelBengtsson** [comment]
Fixed in 8ec4ead6f72c2c118de3e21a0e107b0e3a3b163c
