### ISSUE TITLE
Log Output in successful Checkout Summary - Use of undefined constant KCO_WC_VERSION...

### ISSUE THREAD

**Issue by VonZubinski** [krokedil/klarna-order-management-for-woocommerce#44]
Version: 1.6.0
Payments successful
Logging turned off

Below the WooCommerce checkout summary we get this output:

Warning: Use of undefined constant KCO_WC_VERSION - assumed 'KCO_WC_VERSION' (this will throw an Error in a future version of PHP) in /var/www/web2/htdocs/wp-content/plugins/klarna-order-management-for-woocommerce/includes/class-wc-klarna-logger.php on line 74

Warning: Use of undefined constant KCO_WC_VERSION - assumed 'KCO_WC_VERSION' (this will throw an Error in a future version of PHP) in /var/www/web2/htdocs/wp-content/plugins/klarna-order-management-for-woocommerce/includes/class-wc-klarna-logger.php on line 74

_Temporary fix:_
Changing the constant KCO_WC_VERSION into WC_KLARNA_ORDER_MANAGEMENT_VERSION in class-wc-klarna-logger.php

**Comment by VonZubinski** [comment]
Problem came back today after update to 1.6.1

@MichaelBengtsson and @kristibarbosky could you look into this?

**Comment by kristibarbosky** [comment]
Hi @VonZubinski  -
Apologies for this issue (again).  Per discussion with Krokedil + Klarna, this should be fixed in the latest Woo OM release v1.6.2: https://github.com/krokedil/klarna-order-management-for-woocommerce/releases/tag/1.6.2
