### ISSUE TITLE
Completing order removes taxes from Woo

### ISSUE THREAD

**Issue by broksonic21** [krokedil/klarna-order-management-for-woocommerce#50]
Note; We can repro this with just AvaTax, Woo, and Klarna Payments and Order Management installed, with no custom code.

Here's what happens:
* Place a Klarna order via Woo to state (US) with taxes on it. It's in processing and shows the tax in the admin view  (and purchaser order history)
* Add tracking info manually (or wait for it to ship in real life), it still shows the tax in Woo admin view (and purchaser order history)
* Mark it as "COMPLETED" (which causes Klarna to capture it) - the tax disappears from woo admin view (and purchaser order history)

Note: Klarna (and AvaTax) still believe there's tax - only the Woo Admin View (and thus any analytics or API usage as well) is impacted.

This is impacting a large % of our orders right now, significantly impacting our analysis.

Cancelled or Processing orders aren't impacted - only COMPLETED ones.

**Comment by broksonic21** [comment]
The issue is here: https://github.com/krokedil/klarna-order-management-for-woocommerce/blob/master/includes/class-wc-klarna-order-management-order-lines.php#L113 

specifically $order->calculate_totals

See this debug shell stack - by calling calculate_totals again, the taxes are lost (and thus, it goes from $75.90 down to $72.00). Moving order to COMPLETED has this plugin capture the order, which eventually calls get_order_lines, which eventually leads to this flow, which shows that this code is the impact.

wp> $order = wc_get_order(ORDER_ID);
---- LOTS of DATA ---
wp> intval( round( $order->get_total() * 100 ) )
=> int(7590)
wp> $order->calculate_shipping();
=> string(1) "7"
wp> intval( round( $order->get_total() * 100 ) )
=> int(7590)
wp> $order->calculate_taxes();
=> NULL
wp> intval( round( $order->get_total() * 100 ) )
=> int(7590)
wp> $order->calculate_totals();
=> string(5) "72.00"
wp> intval( round( $order->get_total() * 100 ) )
=> int(7200)

**Comment by broksonic21** [comment]
Note: this only happens with this turned off:

<img width="696" alt="image" src="https://user-images.githubusercontent.com/24306571/98950562-28691800-24c7-11eb-9b79-383d88a3ea4f.png">

With that unchecked, it calls get_order_lines. With that checked, it doesn't.

**Comment by broksonic21** [comment]
This is also https://wordpress.org/support/topic/taxes-removed-from-woo-upon-capture-w-avatax-and-klarna/

**Comment by muntjaber** [comment]
There is a fix for this in the [develop branch](https://github.com/krokedil/klarna-order-management-for-woocommerce/commit/d656d644d72d1d35eca79237543aa2baad9de69d).
