### ISSUE TITLE
Mismatching order total with coupons

### ISSUE THREAD

**Issue by jgangso** [krokedil/klarna-order-management-for-woocommerce#64]
### Steps to reproduce

1. Create order with regular discount coupon (30% discount)
2. Capture order on Woocommerce order admin
3. Review the order on Klarna merchant portal

**Expected:**
Order is captured.

**Current:**
Order is captured, but with notice:

> The captured amount (€118.30) was not equal to the sum of the order lines (€159.19) and this might affect your experience in handling this order.

### Notes

Inspecting the OM logs show the following:

```{
  "id": "da0b35c4-af79-26cf-9b51-xxxxxxxxxxxxx",
  "type": "POST",
  "title": "Capture Klarna order",
  "request": {
    "headers": {
      "Authorization": "Basic xxxxxxxxxxxxx",
      "Content-Type": "application\/json"
    },
    "user-agent": "WordPress\/5.8.3; https:\/\/xxxxxx.fi - WooCommerce: 6.0.0 - OM:1.6.8 - PHP Version: 7.4.23 - Krokedil",
    "method": "POST",
    "body": {
      "order_lines": [
        {
          "reference": "XXXXXX03401BE",
          "type": "physical",
          "name": "XXXXXXXXXXX - 37",
          "quantity": 1,
          "unit_price": 16900,
          "tax_rate": 2400,
          "total_amount": 11830,
          "total_discount_amount": 5070,
          "total_tax_amount": 2290
        },
        {
          "reference": "matkahuolto:2",
          "type": "shipping_fee",
          "name": "Toimitus l\u00e4himp\u00e4\u00e4n Matkahuollon noutopisteeseen",
          "quantity": 1,
          "unit_price": 0,
          "tax_rate": null,
          "total_amount": 0,
          "total_discount_amount": 0,
          "total_tax_amount": 0
        },
        {
          "reference": "Discount",
          "type": "discount",
          "name": "night",
          "quantity": 1,
          "unit_price": 4089,
          "tax_rate": 0,
          "total_amount": 4089,
          "total_discount_amount": 0,
          "total_tax_amount": 981
        }
      ],
      "order_amount": 11830,
      "order_tax_amount": 0,
      "shipping_info": [
        {
          "tracking_number": "",
          "tracking_uri": ""
        }
      ],
      "captured_amount": 11830
    }
  },
```

To my understanding, the method `\WC_Klarna_Order_Management_Order_Lines::process_order_item_coupon ` is supposed to include coupon lines only if `'smart_coupon' === $coupon->get_discount_type() || 'US' === $this->klarna_country`, but the return variable gets a value already in the beginning of the method, making it return the coupon line in any case.

**Comment by montazarr** [comment]
Thanks for filing an issue.

I followed your steps, and used a regular, percentage-discounted coupon to try to reproduce the issue, however, the order was successfully captured without any notice:

```json
	"id": "b6af2f8e-58ba-61b6-b061-xxxxxxxxxxxxx",
	"type": "POST",
	"title": "Capture Klarna order",
	"request": {
		"headers": {
			"Authorization": "Basic xxxxxxxxxxxxx",
			"Content-Type": "application\/json"
		},
		"user-agent": "WordPress\/5.8.3; http:\/\/localhost - WooCommerce: 6.1.0 - OM:1.6.8 - PHP Version: 8.0.10 - Krokedil",
		"method": "POST",
		"body": {
			"order_lines": [{
				"reference": "simple-25-1",
				"type": "physical",
				"name": "Simple 24%",
				"quantity": 1,
				"unit_price": 9999,
				"tax_rate": 2400,
				"total_amount": 6999,
				"total_discount_amount": 2999,
				"total_tax_amount": 1355
			}, {
				"reference": "flat_rate:1",
				"type": "shipping_fee",
				"name": "Flat rate",
				"quantity": 1,
				"unit_price": 6076,
				"tax_rate": 2400,
				"total_amount": 6076,
				"total_discount_amount": 0,
				"total_tax_amount": 1176
			}, {
				"reference": "Discount",
				"type": "discount",
				"name": "night",
				"quantity": 1,
				"unit_price": 2419,
				"tax_rate": 0,
				"total_amount": 2419,
				"total_discount_amount": 0,
				"total_tax_amount": 581
			}],
			"order_amount": 13075,
			"order_tax_amount": 0,
			"shipping_info": [{
				"tracking_number": "",
				"tracking_uri": ""
			}],
			"captured_amount": 13075
		}
	},
```

The [conditional](https://github.com/krokedil/klarna-order-management-for-woocommerce/blob/ac5df6725a814a48afda8fb66582feaa00814e9d/includes/class-wc-klarna-order-management-order-lines.php#L280) that you refer to only adds additional fields if it is satisfied. We always add coupon lines [if the order contains](https://github.com/krokedil/klarna-order-management-for-woocommerce/blob/ac5df6725a814a48afda8fb66582feaa00814e9d/includes/class-wc-klarna-order-management-order-lines.php#L161) any coupon. The [prepared array of coupon items](https://github.com/krokedil/klarna-order-management-for-woocommerce/blob/ac5df6725a814a48afda8fb66582feaa00814e9d/includes/class-wc-klarna-order-management-order-lines.php#L243) is [always returned](https://github.com/krokedil/klarna-order-management-for-woocommerce/blob/ac5df6725a814a48afda8fb66582feaa00814e9d/includes/class-wc-klarna-order-management-order-lines.php#L292) at the end of the function, like you noted.

**Comment by jgangso** [comment]
Thanks for feedback. I see my description was unclear regarding the notice.
The notice appears in the Klarna Merchant panel, not in Woocommerce. Can you see any notice in Klarna panel?

**Comment by montazarr** [comment]
I apologize for the belated reply @jgangso!

The issue that you've reported should now be resolved.
