### ISSUE TITLE
Fatal error with release 1.8.0

### ISSUE THREAD

**Issue by gogasan24ru** [krokedil/klarna-order-management-for-woocommerce#93]
We have accidentally tested release 1.8.0 with 4.8.1 WC version and got fatal error:
```2023-06-22T09:27:22+00:00 CRITICAL Uncaught Automattic\WooCommerce\Vendor\League\Container\Exception\NotFoundException: Alias (Automattic\WooCommerce\Internal\DataStores\Orders\CustomOrdersTableController) is not being managed by the container or delegates in /EDITED/wp-content/plugins/woocommerce/vendor/league/container/src/Container.php:188
Stack trace:
#0 /EDITED/wp-content/plugins/woocommerce/src/Internal/DependencyManagement/ExtendedContainer.php(116): Automattic\WooCommerce\Vendor\League\Container\Container->get()
#1 /EDITED/wp-content/plugins/woocommerce/src/Container.php(72): Automattic\WooCommerce\Internal\DependencyManagement\ExtendedContainer->get()
#2 /EDITED/wp-content/plugins/klarna-order-management-for-woocommerce/classes/class-wc-klarna-meta-box.php(49): Automattic\WooCommerce\Container->get()
#3 /EDITED/wp-includes/class-wp-hook.php(310): WC_Klarna_Meta_Box->kom_meta_box()
#4 /EDITED/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /EDITED/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /EDITED/wp-admin/includes/meta-boxes.php(1701): do_action()
#7 /EDITED/wp-admin/edit-form-advanced.php(271): register_and_do_post_meta_boxes()
#8 /EDITED/wp-admin/post-new.php(75): require('/mnt/BLOCKSTORA...')
#9 {main}
  thrown in /EDITED/wp-content/plugins/woocommerce/vendor/league/container/src/Container.php on line 188

```
On WC product edit page or WC order edit page.

Reverting to 1.7.2 solved issue.
Please add version check for feature you using and update `WC requires at least` plugin header value. 

Issue is reproduced on clean WP (6.2.2) + WC (4.8.1) + KOM (1.8.0) installation.

Actual behavior:
When visiting `/wp-admin/post-new.php?post_type=shop_order` getting fatal error message.

Expected behavior:
When visiting `/wp-admin/post-new.php?post_type=shop_order` getting order creation page.

**Comment by mntzrr** [comment]
Hello @gogasan24ru ! Which version of PHP is the site running? If I downgrade to PHP 7.1, I can recreate the issue, however, upgrading to anything newer (>= 7.2) solved the issue. 

The function that was added in 1.8.0 was introduced in WooCommerce v4.4.0, and since you're running a later version of WC, it should be available. We'll still bump the required WC version to 5.0 as v4.4.0 is three years old now.

**Comment by gogasan24ru** [comment]
Issue appeared at installation with PHP version  7.4.33	@mntzrr 
Thanks for feedback.

**Comment by mntzrr** [comment]
Thank you! I managed to recreate the issue in more recent versions of PHP as well. This issue has been addressed in the PR above.

If you wish to test the PR in a staging environment, you can use this [branch](https://github.com/krokedil/klarna-order-management-for-woocommerce/tree/develop-fatal-error-with-release-180).

**Comment by gogasan24ru** [comment]
Seems working now with 1.8.1. Thanks!
